#!/bin/bash

[ ! "$(playerctl -p spotify status 2>&1)" = "Playing" ] && exit 33;

# Define cursor icons
ICON=#cc6666
FOREGROUND=#eceff4
                           
songTitle="$(playerctl metadata title)"
songArtist="$(playerctl metadata artist)"
songInfo="$songTitle - $songArtist ";

#Display output
echo -ne "^c${ICON}^ ^c${FOREGROUND}^${songInfo}";
